### ISSUE TITLE
"Clearing" A Dataset

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#102]
This is probably a larger discussion, but it seems like there is no notion of "clearing" a dataset, or starting a "new" dataset. There's a usability trade off in every direction here, but the current approach of _just-keep-adding-to-the-pile_ seems like it hasn't been considered properly, and means that I have to do all of my refinebio work in an incognito tab.

**Comment by dongbohu** [comment]
@dvenprasad Does it make sense to add a "Clear Dataset" button when the dataset is not empty?

**Comment by dvenprasad** [comment]
![screen shot 2018-07-25 at 10 26 31 am](https://user-images.githubusercontent.com/15315514/43207600-6546c262-8ff6-11e8-8d76-41397f2372ff.png)

I think the 'Clear dataset' should be triggered on the Download page. Having a 'Remove All' button in the Samples section on the downloads page is a good way to go about this. 

Users will spend a good chunk of their time and effort to build the dataset and it shouldn't be too easy for them clear dataset accidentally, especially since we have no mechanism in place for recovery or undo. 'Remove all' button on the download page will give the users an opportunity to review what they are removing from their dataset and less likely to remove it by accident.

This fix is assuming that the dataset is automatically cleared when a smash job is kicked off at the backend.

**Comment by Miserlou** [comment]
I'd like to throw in the idea of having a confirmation dialog box, as I have already deleted my dataset by mistake once.

**Comment by dongbohu** [comment]
@dvenprasad: I talked to @cgreene briefly about this issue. We decided to move this button to `Download` page for now. 

I will also add a confirmation dialog box before the action.

**Comment by dongbohu** [comment]
@dvenprasad It seems a little too hard for users to find this new button when it is on the right side of the `Samples` table. Does it make more sense to put it on the right side of `Share Dataset` button?

**Comment by dvenprasad** [comment]
@dongbohu What is the use case are you thinking about?

**Comment by dongbohu** [comment]
@dvenprasad Suppose a user adds some experiment or sample data, but for some reason he/she wants to start from scratch. I feel that the button that clears the whole dataset should be easy for the user to find. When the button is on the right side of "Samples" table, it is in the middle of the `Download` page, and it is only affiliated with samples. 

Since this button affects the whole dataset, it seems to make more sense to put it together with "Share Dataset" button. Just my two cents.

**Comment by dongbohu** [comment]
Solved by PR #181.
