### ISSUE TITLE
Modal Doesn't Fit On Page

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#114]
<img width="1561" alt="screen shot 2018-07-05 at 6 29 39 pm" src="https://user-images.githubusercontent.com/139987/42351151-73631848-8081-11e8-864c-b71155281f8d.png">

**Comment by arielsvn** [comment]
What would be our options here @dvenprasad? Reduce the height of the modal dialog and add a scroll bar inside of it?

I kind of like the current approach, where we put a single scroll bar at the right of the window to scroll the modal dialog.

![image](https://user-images.githubusercontent.com/1882507/43861811-ef8ee208-9b25-11e8-8719-b126541ecbee.png)

**Comment by dvenprasad** [comment]
I would recommend to add a scroll bar for the table and keep the table headers sticky.

**Comment by arielsvn** [comment]
> I would recommend to add a scroll bar for the table and keep the table headers sticky.

This can be a good solution for the modal with the Samples table, but what about others?? For example:

![2018-08-27 14 22 56](https://user-images.githubusercontent.com/1882507/44677761-bfd81280-aa04-11e8-8341-7ab76445fead.gif)

Besides the obvious cosmetic details, @dvenprasad what do you think of this interaction? Even if the modal dialog doesn't fit vertically, the user can scroll as if it were the entire page. Do you think we should put the scrollbar inside the dialog instead??

I like this approach because it's consistent across all screen sizes. On a landscape iphone the experience might not be as good if the user can only scroll the dialog content.

![2018-08-27 14 27 57](https://user-images.githubusercontent.com/1882507/44678053-6e7c5300-aa05-11e8-9afa-6b5c97a466cd.gif)

**Comment by dvenprasad** [comment]
@arielsvn and I chatted about this a little.  We decided that we would leave the modal element as is but add scrollbar to the table element and keep the table headers sticky.
