### ISSUE TITLE
Cannot navigate forward on browser

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#141]
From the search results page, navigate to an experiment page, then hit the back button on the browser. This takes the user back to the search page but cannot use the forward button on the browser to go back to the experiment page.

**Comment by arielsvn** [comment]
For the record: This bug was caused because we always update the browser url after every search. This is done by calling `history.push`. When navigating back from an experiment page, this update is triggered, which adds a new entry in the browser history removing the entry for the experiments page, and disabling the forward arrow.

This is the default behavior of `history.push`, adding a new entry in the browser history even though there won't be any change in the url. There's some discussion around it, such as https://github.com/ReactTraining/history/issues/470. 

I used some of the suggestions and modified the behavior of `history` in https://github.com/AlexsLemonade/refinebio-frontend/pull/230/commits/604b269914b1e57f445f15ff08db4ea8dd576cf3
