### ISSUE TITLE
Pubmed ID is duplicated as 'Submitter'

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#151]
In the detail view, there is a field called 'Submitter' that appears to be a duplicate of the Pubmed ID.

![screen shot 2018-07-16 at 10 28 08 am](https://user-images.githubusercontent.com/139987/42764207-0b1fdcb6-88e3-11e8-838f-1eb90793f531.png)

**Comment by Miserlou** [comment]
Ex: https://staging.refine.bio/experiments/54

**Comment by Willv19** [comment]
I found the location of this field in the code, and it is just using the PubMed ID.
https://github.com/AlexsLemonade/refinebio-frontend/blob/e997a1e17345f8d1e46d02c10d8115a850454245/src/containers/Experiment/index.js#L147-L150

Would it make the most sense to just delete this extra field, or is there something else that should be populating it?

**Comment by Miserlou** [comment]
I don't even know what Submitter is supposed to _actually be_ here, since title, institution and PMID are already there. Maybe it can just be deleted?

**Comment by Miserlou** [comment]
@dvenprasad

**Comment by dvenprasad** [comment]
It's supposed to pull the name from the contact field from experiment annotations. 

![screen shot 2018-07-16 at 2 35 43 pm](https://user-images.githubusercontent.com/15315514/42776616-8d9b61de-8905-11e8-9717-e06986373a51.png)

**Comment by Willv19** [comment]
For the example @Miserlou posted, this is the contact name that I could find by looking through the annotations: 'Rogier,,Versteeg'. I might be looking in the wrong place, though. This was in the data.contributer field in the annotations.

**Comment by cgreene** [comment]
I'm also noticing that there is a PMID but no associated publication. Is that a known issue b/c we haven't filled that in yet, or is that a separate bug? I think this is the publication:
https://www.ncbi.nlm.nih.gov/pubmed/22367537

**Comment by jaclyn-taroni** [comment]
@dvenprasad is there something we're hearing from users about the submitter info? I think it is more likely that folks will want to search by _authors_ of the linked publication rather than submitter

**Comment by dvenprasad** [comment]
Users weren't too concerned about Submitter info but more about Authors. 

To have 'Submitter' was part of the design before the usability evals. Users generally reached out to the Submitter for additional details about the data/collaboration/ for raw data.

So if we are grabbing all authors from Pubmed (https://github.com/AlexsLemonade/refinebio/issues/214) then we can remove 'Submitter' field and replace it with 'Authors' field.
Otherwise, we will need to populate 'Submitter Info' correctly. The users will have at least one point of contact with the people who generated the data.

**Comment by Willv19** [comment]
This relies on https://github.com/AlexsLemonade/refinebio/issues/214 landing
