### ISSUE TITLE
Downloads Page: Populate "Download Files Summary" dynamically

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#25]
## Description

Via #6 
For matrices that each represent a single sample, each matrix will have 2 columns a gene column and a value column. Assuming they are roughly equal (which is in fact an assumption) the rough math is that we'll need the size of one gene column plus the size of each matrix's value column.

To make this clear and to demonstrate the nesting of objects, I have written out the algorithm in python:

```
def get_matrix(sample):
    all_files = []
    for result in sample.results:
        for file in result.files:
            if ".PCL" in file.filename:
                return file


def calculate_size_of_aggregates(samples):
    experiments = group_by_experiment(samples)
    total_size = 0

    for experiment in experiments:
        # Need size of gene column for the first matrix.
        experiment_size = .5 * get_matrix(experiment[0]).size_in_bytes
        for sample in experiment:
            file = get_matrix(sample)

            # Need size of value column for every sample.
            experiment_size = experiment_size + .5 * file.size_in_bytes

        total_size = total_size + experiment_size

    return total_size
```

Note that if the data is aggregated by species instead of experiments then it will be the same thing, just replace experiment with species.

## Mockup
![screen shot 2018-05-18 at 2 46 38 pm](https://user-images.githubusercontent.com/4724065/40252429-4bc9df76-5aaa-11e8-8eab-f711f9470b0f.png)

**Comment by ramenhog** [comment]
@Miserlou we talked about this once a while back and you had mentioned that the backend will be able to give the frontend these stats surrounding a dataset via the api. Is this still the case/is there an issue created for it?

**Comment by arielsvn** [comment]
Talked with @kurtwheeler about this. https://github.com/AlexsLemonade/refinebio/issues/221#issuecomment-386425109 contains metadata information of a download when aggregated by experiment. In that example the following files are returned:

```
"all_metadata.json",
"README.txt",
"LICENSE.txt",
"E-GEOD-123/samples_metadata.tsv",
"E-GEOD-123/experiment_metadata.json",
"E-GEOD-123/E-GEOD-123.PCL",
"E-GEOD-456/samples_metadata.tsv",
"E-GEOD-456/experiment_metadata.json",
"E-GEOD-456/E-GEOD-456.PCL"
```

The following categories should be displayed when estimating the file sizes:

- Gene Expression Matrices (`"E-GEOD-123/E-GEOD-123.PCL"` and `"E-GEOD-456/E-GEOD-456.PCL"`). The size of these files should be estimated using Kurt's algorithm above. In that case the algorithm is taking into consideration all the samples inside the dataset, that's why it's grouping them by experiment.

- Sample Metadata Files (`"E-GEOD-123/samples_metadata.tsv"` and `"E-GEOD-456/samples_metadata.tsv"`). There will be one of these files for each experiment. We can estimate their size by multiplying the number of samples on each experiment times a **constant** representing the size of the metadata of each sample.

- Experiment Metadata (`"E-GEOD-123/experiment_metadata.json"` and `"E-GEOD-456/experiment_metadata.json"`). The size of each one of these files will be constant.

The remaining files file size won't be displayed independently but their sizes should be estimated and added to the total.

- The size of `all_metadata.json` is equal to the sum of the sizes of the Sample Metadata Files and the experiment metadata files together.

**Comment by kurtwheeler** [comment]
I'm Kurt Wheeler and I support this message!
