### ISSUE TITLE
On the about page, only count the organisms with QN targets in "supported organisms"

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#320]
Related: https://github.com/AlexsLemonade/refinebio/issues/642
I believe @kurtwheeler is filing a backend ticket related to this, at which point there will be more information.

**Comment by kurtwheeler** [comment]
This is the ticket for that: https://github.com/AlexsLemonade/refinebio/issues/644

That ticket is light on implementation details because they haven't been worked out yet.

**Comment by jaclyn-taroni** [comment]
There was a conversation in Slack about making sure the numbers on the about page are correct in general, but AFAIK there is no ticket to track that on the frontend or the backend? Should we file an additional ticket @arielsvn ?

**Comment by arielsvn** [comment]
I think we can keep track of that in this ticket.

In the case of the about page, will it be sufficient to update the numbers
weekly or something like that? We can add them to a configuration file.

That way we won't have to expose this information in the API.

**Comment by kurtwheeler** [comment]
> In the case of the about page, will it be sufficient to update the numbers
weekly or something like that? We can add them to a configuration file.

I think that will be good. I do think it'd be nice to have these pulled from an endpoint so that we don't have to do this manually and so it can be more up-to-date (which will be cool while we're increasing the numbers hourly or daily). Once we get the bandwidth I'm thinking that we could have the foreman update the numbers regularly and then just make them available via a simple table or something.

**Comment by arielsvn** [comment]
With https://github.com/AlexsLemonade/refinebio-frontend/issues/64 we added statics to the landing page, we can use them to calculate the numbers on the about page as well.

At the moment we have around 96k samples and 10 organisms (we'll know the total data downloaded with https://github.com/AlexsLemonade/refinebio/issues/768).

@dvenprasad we should also update the copy on the about page, to indicate that we're showing current numbers now.

**Comment by dvenprasad** [comment]
Updated copy:

https://invis.io/JANIXFWB29G#/314342370_about-Page_Copy_4

Let me know if you need anything else, @arielsvn
