### ISSUE TITLE
Tables need revamping

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#365]
Based on feedback from UE:

- Horizontal scrolling was hard, making it difficult to discover "hidden" fields
- Provide a mechanism to filter through the table
- make it "compact" ( on  design level, revisit cell padding)

**Comment by dvenprasad** [comment]
![img_20181011_104824](https://user-images.githubusercontent.com/15315514/46813852-7558ee00-cd45-11e8-8623-374151fee650.jpg)

![img_20181011_104841](https://user-images.githubusercontent.com/15315514/46813851-7558ee00-cd45-11e8-9701-4ffd4ba059f2.jpg)


Gonna mockup what I can and summarize recommendations.

**Comment by dvenprasad** [comment]
![new-table annotated](https://user-images.githubusercontent.com/15315514/46831815-62104780-cd72-11e8-8db5-92db27b715ee.png)


![experiment-page copy](https://user-images.githubusercontent.com/15315514/46831885-9f74d500-cd72-11e8-99c1-e5ddb1f299f6.png)

Annotated on Invision: https://invis.io/VWOJF7ZFTD7#/325148047_experiment-Page_Copy

Sort icons are in assets/icons

@arielsvn  let me know if you need anything else.

**Comment by arielsvn** [comment]
Added an issue on the backend to add the ability to filter samples https://github.com/AlexsLemonade/refinebio/issues/739

**Comment by arielsvn** [comment]
@dvenprasad I submitted a PR #394 implementing the cosmetic changes to the table, and also another issue #395 to keep track of the filtering.

Only detail missing is partially showing the last column so that users know they can scroll. I couldn't find a non ugly/hacky way to do this, but with the improvements from #394 the same will happen most of the time. I think it would be good to see these improvements working with real data to evaluate if we still need the last column thing.
