### ISSUE TITLE
Filter numbers do not update when filter is applied

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#374]
When I filter by organism, I would expect the technology numbers to update to only include the samples from that organism.

![2018-10-08 09 42 00](https://user-images.githubusercontent.com/19534205/46612502-b7342b00-cade-11e8-99b0-d7e90eceba57.gif)

**Comment by kurtwheeler** [comment]
The reason the filters work like this is because the filters are applied as soon as you click the checkbox. So say you wanted to filter to both `Danio rerio` and `Gallus gallus`. If we updated the filters and their numbers after you checked `Danio rerio`, you wouldn't be able to click on `Gallus gallus` any more because there would be 0 `Gallus gallus` samples in the dataset since you've already filtered it to only include `Danio rerio`.

Therefore I think the way we should address this issue is to add an `apply` button. This way I can click BOTH `danio rerio` and `gallus gallus` before either one of the filters are applied. We'd then show a new set of search results that are filtered to include those organisms, and then we could display updated filters and filter numbers.

**Comment by kurtwheeler** [comment]
cc @dvenprasad since that's a UX change.

**Comment by dvenprasad** [comment]
What Kurt's describing is called Batch Filtering. 

Batch filtering is great when the users *always* know exactly which filters they want to apply. Interactive filters (the one we have)  is good when users want to explore. 

Most of our users fall in group that would like to explore and we should go with interactive filtering. 

[Macy's](https://www.macys.com) has a pretty good implementation of interactive filtering.

![2018-11-02 11 06 04](https://user-images.githubusercontent.com/15315514/47923982-2b20e380-de91-11e8-8590-f45367229d00.gif)

When a filter is applied to a cateogry, update all others except the category in which the filter is applied. 
When a 2nd category is applied, then update all other categories and retain the applied options even if the number is 0. 

For example: If a user applies filter on Organism, update all others except Organism. 
When the user applies another filter on Technology, update all the others and retain the applied filter in Organisms.

**Comment by arielsvn** [comment]
Had a discussion with @kurtwheeler about this...

I was thinking of implementing this only in the front-end, and calculate the filters based on the previous state and the last filter applied. But we want users to be able to share the url and see the same page/filters, so the filters will have to be calculated on the backend.

The filters will be calculated in the following way:

- For the last category that was applied, we count the samples after applying every filter that is not in this category.

- For the remaining categories we calculate them applying all filters.

We'll try to get the last applied filter from the URL.

![img_6012](https://user-images.githubusercontent.com/1882507/48085855-6db42a00-e1c9-11e8-88b2-2ece2992f4f7.jpg)

**Comment by arielsvn** [comment]
https://github.com/AlexsLemonade/refinebio/pull/835 will add support in the backend for the interactive filtering, however the frontend should also be updated so that the filters appear in the URL in the same order that they were applied.
