### ISSUE TITLE
Handle timeouts on samples table more properly

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#429]
https://www.refine.bio/experiments/GSE54716#samples

<img width="1320" alt="screen shot 2018-11-09 at 1 40 56 pm" src="https://user-images.githubusercontent.com/139987/48289675-2c1fbb00-e425-11e8-8e6e-d03fe9449047.png">

**Comment by Miserlou** [comment]
This looks like it it's probably the result of API timeout, we should figure out a better way to request this information, but it should handle timeouts more properly.

**Comment by arielsvn** [comment]
Yeah definitely! it worked for me, but the request took 24 secs

**Comment by arielsvn** [comment]
The samples table is also not loading correctly for experiment with a lot of samples. This is probably because we're sending all sample accession codes in order to get detailed information for them. 

We should update the API so that it can receive an experiment accession code to return detailed information of the samples of that experiment.

[Sentry issue](https://sentry.io/greenelab/refinebio-frontend/issues/756686001/?referrer=github_plugin)
