### ISSUE TITLE
Direct access of resources is broken again

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#435]
https://www.refine.bio/results?q=

![screen shot 2018-11-26 at 7 56 19 pm](https://user-images.githubusercontent.com/139987/49051322-5d361480-f1b5-11e8-9ac6-29d188027f78.png)

**Comment by arielsvn** [comment]
Fixed this by creating a new redirection rule, so that 404 errors are redirected to `/index.html`. I had done this before but not sure why the rule wasn't there. Did we change the configuration in cloudfront?

![image](https://user-images.githubusercontent.com/1882507/49383876-c3f08c00-f6e7-11e8-8070-77786686e207.png)

**Comment by Miserlou** [comment]
Does this require any Terraform work?
