### ISSUE TITLE
Dashboard wish list

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/refinebio-frontend#453]
At a glance, we'd like to know: 1) Is the system running? 2) Is it going "fast" / how fast is it going?

More specifically, it would be useful to display:
- Number of samples processed per unit time (most likely hour) over the last day and the last week
- Number of samples we have downloaded but not yet processed
- Total number of samples processed

I've touched base with the communications team and it would be useful for them to know how many samples have been **downloaded by users**. Not sure if this is in scope, but wanted to make sure it was noted somewhere.

**Comment by jaclyn-taroni** [comment]
Related: https://github.com/AlexsLemonade/refinebio/issues/707

**Comment by kurtwheeler** [comment]
https://github.com/AlexsLemonade/refinebio/pull/880 is almost out, which changes the stats endpoint to return a response like:
```
{
    "survey_jobs": {
        "total": 23707,
        "pending": 23354,
        "completed": 347,
        "successful": 326,
        "open": 0,
        "average_time": 27.287414
    },
    "downloader_jobs": {
        "total": 6846,
        "pending": 6728,
        "completed": 96,
        "successful": 72,
        "open": 0,
        "average_time": 21.284127
    },
    "processor_jobs": {
        "total": 194,
        "pending": 78,
        "completed": 84,
        "successful": 60,
        "open": 6,
        "average_time": 59.568368
    },
    "samples": {
        "total": 6562
    },
    "experiments": {
        "total": 317
    },
    "input_data_size": 571874661,
    "output_data_size": 0,
    "active_volumes": [
        "0"
    ],
    "nomad_running_jobs": 0,
    "nomad_pending_jobs": 0,
    "nomad_running_jobs_by_type": {
        "SURVEYOR": 0,
        "NO_OP": 0,
        "DOWNLOADER": 0,
        "SMASHER": 0,
        "AFFY_TO_PCL": 0,
        "TRANSCRIPTOME_INDEX": 0,
        "ILLUMINA_TO_PCL": 0,
        "JANITOR": 0,
        "SALMON": 0
    },
    "nomad_pending_jobs_by_type": {
        "SURVEYOR": 0,
        "NO_OP": 0,
        "DOWNLOADER": 0,
        "SMASHER": 0,
        "AFFY_TO_PCL": 0,
        "TRANSCRIPTOME_INDEX": 0,
        "ILLUMINA_TO_PCL": 0,
        "JANITOR": 0,
        "SALMON": 0
    },
    "nomad_running_jobs_by_volume": {
        "volume_0": 0
    },
    "nomad_pending_jobs_by_volume": {
        "volume_0": 0
    }
}
```

These changes are mostly just adding new fields, however the database jobs stats (i.e. survey_jobs,  downloader_jobs, processor_jobs) now have an `open` field which means jobs that are currently represented as actively running in the database. The `pending` field now strictly represents jobs that haven't been marked as started in the database yet.

The `data_downloaded` field has gone away because it wasn't accurate. Instead we now have `input_data_size` and `output_data_size`. This is the amount of data we've successfully processed, with input being the size of the raw data and the output being the size of the processed data.

There is now an active volumes field, which is a list of the volumes which are currently mounted onto an active instance. The length of this list can be used to determine how many instances we have up.

The rest of the new fields relate to the number of nomad jobs. They are provided as a total broken down into pending and running (`nomad_running_jobs` and `nomad_pending_jobs`), running and pending jobs broken down by the type of job, and then pending and running jobs broken down by the volume index they are running on. There are few job types that aren't specific to an index, so these will simply not be included. Therefore the sum of `nomad_running_jobs_by_type` should be equal to `nomad_running_jobs`, but not the sum of `nomad_running_jobs_by_volume`.

Finally, this should give us everything we need to have a general health score of "running fast", "running", and "not running".
 
We are "running fast" if we have:
  * > 5 active volumes AND
  * > 200 running nomad jobs.
We are "running" if we have:
  * > 5 active volumes AND
  * > 50 running nomad jobs AND < 200 running nomad jobs
We are "not running" if we have:
  * < 5 active volumes OR
  * < 50 running nomad jobs

@Miserlou would you agree with those classifications?

**Comment by arielsvn** [comment]
Started working on the executive dashboard. @kurtwheeler I might need your help with some of the following items:

- Number of samples processed in the last hour
- Number of samples processed over time. Can be calculated from the nomad jobs completed over time?
- Number of samples in the processing queue. Can this be calculated somehow from the number of pending jobs?

**Comment by arielsvn** [comment]
Had a discussion a few days ago with @kurtwheeler, we won't be able to calculate the number of samples in the processing queue.

**Comment by dvenprasad** [comment]
Documenting mockups and links to Invision mockups

Mockups
![exec-dashboard-organism-breakdown](https://user-images.githubusercontent.com/15315514/52223608-006d6f00-2874-11e9-94ae-7c41902b2880.png)
![exec-dashboard-organism-breakdown-sonic-fast](https://user-images.githubusercontent.com/15315514/52223609-01060580-2874-11e9-9275-7200ae1931fa.png)
![exec-dashboard-tech-breakdown-not-running](https://user-images.githubusercontent.com/15315514/52223610-01060580-2874-11e9-8d6f-d8a51819e646.png)


Invison: 
https://invis.io/ZFQ7LZ686EJ#/343478539_exec-Dashboard-Organism-Breakdown

https://invis.io/9ZQBTWRA824#/343478537_exec-Dashboard-Tech-Breakdown-Not-Running

https://invis.io/BUQBTXOSTH4#/343478538_exec-Dashboard-Organism-Breakdown-Sonic-Fast

**Comment by arielsvn** [comment]
Executive dashboard can be seen at https://www.refine.bio/executive-dashboard

Append `?tv` to get the [TV optimized version](https://www.refine.bio/executive-dashboard?tv).
