### ISSUE TITLE
Add Aggregation and transformation stats to dashboard

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#548]
I was chatting with @jaclyn-taroni and it would be useful to know how people are aggregating their datasets. We can also track which transformations users are using on their datasets.

**Comment by Miserlou** [comment]
Similarly, are users selecting individual samples or using entire experiments.

**Comment by arielsvn** [comment]
> Similarly, are users selecting individual samples or using entire experiments.

@Miserlou is there a way that we could calculate that in a separate script?

Seems that there's no fast way of calculating this, given that the samples in a dataset are stored in a `JSONField` which is not queryable. According to @jaclyn-taroni we're expecting most users to add entire experiments instead of individual samples.

**Comment by arielsvn** [comment]
![image](https://user-images.githubusercontent.com/1882507/54538922-88629080-496b-11e9-8f79-12d9ad492632.png)
