### ISSUE TITLE
Add package version information to Processing Information Modals

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#65]
https://github.com/AlexsLemonade/refinebio-frontend/issues/22 Introduced the Processing information Modals.

We need to add version information on these modal dialogs for each sample.

![image](https://user-images.githubusercontent.com/1882507/41056420-1afae01a-6992-11e8-8b23-3c04e12c8999.png)

This information should be exposed from the backend AlexsLemonade/refinebio#229

**Comment by dongbohu** [comment]
@ramenhog As you may have seen in this issue:
https://github.com/AlexsLemonade/refinebio/issues/229
Right now we couldn't decide the best approach to collect version information on back end. I have filed a PR:
https://github.com/AlexsLemonade/refinebio/pull/313
which builds a generic API that will return version information of the whole system (instead of per sample). Do you think this API is good enough for you to start working on the current issue?

**Comment by jaclyn-taroni** [comment]
Here you go @ramenhog,  let me know if anything is unclear

```
['Submitter-processed']

The gene identifiers were detected and converted to Ensembl gene IDs using our [custom mappings](https://github.com/AlexsLemonade/identifier-refinery) and [pipeline](link to smasher docs).

['Affymetrix SCAN']

SCAN.UPC: 2.20.0
Brainarray: 22.0.0

['Illumina SCAN']

Illumina Bioconductor annotation packages: 1.26.0

['tximport', 'Salmon']

Salmon: 0.9.1
tximport: 1.6.0
Genome build: GRCh38.p12
```

Some notes:

* Used the current human build for `Genome build`
* SCAN has been newly adapted for Illumina Bead Arrays and is currently only "lives" within our system/code base rather than in the SCAN.UPC package. @dvenprasad do you have any thoughts on how to capture/convey that?
* In the submitter-processed case, we've developed our own mapping and pipelines. (I link to the AlexsLemonade/identifier-refinery repo above.) We obviously don't have any documentation yet. I would be interested to hear 1) @dvenprasad's opinion about where we should link to and 2) what user testing suggests folks want to know in these cases where the "package versioning" is a bit more complicated.

**Comment by jaclyn-taroni** [comment]
Ah, here's where I got those four pipelines from: https://github.com/AlexsLemonade/refinebio-frontend/issues/22#issuecomment-394408631

**Comment by ramenhog** [comment]
Perfect @jaclyn-taroni. Thanks!!

**Comment by dvenprasad** [comment]
- For the SCAN which "lives" within refine.bio, we should treat it as a different process than SCAN. UPC. The copy displayed on the processing info modal should briefly describe what our version of SCAN is and be clearly distinguish from SCAN.UPC. It can be called something along the lines of  illumina-SCAN or SCAN-Bead array. In future, it maybe useful to separate out our version of SCAN as a library so people could download it if they wanted. It may also make it easier for users to track changes in the versions. 

- For the identifier-refinery,  we can link to the repo for now and ensure that the README has sufficient information for someone who has been redirected there from refine.bio. This is a hack and we can remove it once we have docs ready.

In addition, I think we should add a separate section in our docs (https://github.com/AlexsLemonade/refinebio/issues/184) dedicated to packages developed by the CCDL.

**Comment by jaclyn-taroni** [comment]
Illumina SCAN is the same general approach as the Affymetrix processor. We should update the Illumina SCAN copy on the modal to reflect this. See below:

_SCAN (Single Channel Array Normalization) is a normalization method for single channel microarrays that allows us to process individual samples. It was originally developed for Affymetrix microarrays. In our system, it has been adapted for Illumina BeadArrays. SCAN models and corrects for the effect of technical bias, such as GC content, using a mixture-modeling approach. For more information about this approach, see the primary publication (Piccolo, et al. Genomics. 2012. DOI: 10.1016/j.ygeno.2012.08.003)._
