### ISSUE TITLE
Dashboard: OB1hr error in times?

### ISSUE THREAD

**Issue by cgreene** [AlexsLemonade/refinebio-frontend#733]
It looks like we might have an OB1 error in the dashboard for hours. The most recent hour appears to be potentially a combination of the two most recent hours (or else the time is just wrong) - or perhaps the most recent complete hour + the partial hour being calculated. The least recent hour always has a total job/etc count of zero, even when it didn't in the hour before.

**Comment by davidsmejia** [comment]
It's my understanding that the chart should display 9pm yesterday to 8pm today, since its 8:40ishpm now. That would be 24 hours (units) of totals.

I think there is an extra hour being presented when the timeline gets formatted for the chart.

Below is the response from the API, a screen shot of the current chart, and a screenshot of the chart with what appears to be a more accurate timeline.

**This is the data that is being represented:**

```[
  {
    "start": "2019-08-23T01:00:00Z",
    "total": 83
  },{
    "start": "2019-08-23T02:00:00Z",
    "total": 244
  },{
    "start": "2019-08-23T03:00:00Z",
    "total": 214
  },{
    "start": "2019-08-23T04:00:00Z",
    "total": 209
  },{
    "start": "2019-08-23T05:00:00Z",
    "total": 1008
  },{
    "start": "2019-08-23T06:00:00Z",
    "total": 239
  },{
    "start": "2019-08-23T07:00:00Z",
    "total": 278
  },{
    "start": "2019-08-23T08:00:00Z",
    "total": 347
  },{
    "start": "2019-08-23T09:00:00Z",
    "total": 471
  },{
    "start": "2019-08-23T10:00:00Z",
    "total": 179
  },{
    "start": "2019-08-23T11:00:00Z",
    "total": 79
  },{
    "start": "2019-08-23T12:00:00Z",
    "total": 149
  },{
    "start": "2019-08-23T13:00:00Z",
    "total": 1571
  },{
    "start": "2019-08-23T14:00:00Z",
    "total": 568
  },{
    "start": "2019-08-23T15:00:00Z",
    "total": 731
  },{
    "start": "2019-08-23T16:00:00Z",
    "total": 756
  },{
    "start": "2019-08-23T17:00:00Z",
    "total": 251
  },{
    "start": "2019-08-23T18:00:00Z",
    "total": 341
  },{
    "start": "2019-08-23T19:00:00Z",
    "total": 88
  },{
    "start": "2019-08-23T20:00:00Z",
    "total": 86
  },{
    "start": "2019-08-23T21:00:00Z",
    "total": 37
  },{
    "start": "2019-08-23T22:00:00Z",
    "total": 285
  },{
    "start": "2019-08-23T23:00:00Z",
    "total": 1092
  },{
    "start": "2019-08-24T00:00:00Z",
    "total": 1922
  }]
```


**This is 8:43pm on production (displaying the extra unit with no value in the beginning)**
<img width="1096" alt="Screen Shot 2019-08-23 at 8 42 52 PM" src="https://user-images.githubusercontent.com/1075609/63630256-b917b780-c5e6-11e9-9bdf-d2ca19379fad.png">

**And this is without **
<img width="1097" alt="Screen Shot 2019-08-23 at 8 43 02 PM" src="https://user-images.githubusercontent.com/1075609/63630268-dc426700-c5e6-11e9-912c-c840a1d76f10.png">

**Comment by davidsmejia** [comment]
Also I think the partial hour is also being included in the API response. I'll check that out.
