### ISSUE TITLE
Exec Dashboard says it's running really fast, even when low number of samples are being processed 

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/refinebio-frontend#736]
<img width="1635" alt="Screen Shot 2019-08-25 at 8 55 23 PM" src="https://user-images.githubusercontent.com/15315514/63662210-df6e5c00-c77a-11e9-9c16-05479e9254d3.png">

**Comment by cgreene** [comment]
Yea - I've been noticing that. It seems to be based on the underlying samples-being-processed numbers, which are pretty good right now (~500-1k/hr), but it shows the number of samples available download (6 in the hour that you linked).

I'd also note that the number is _highly_ variable because it's only based on the most recent hour. The hour before this was 37 samples, and then the next hour it's ~1k.

![Screen Shot 2019-08-26 at 8 05 23 AM](https://user-images.githubusercontent.com/542643/63689592-60a80c00-c7d8-11e9-928f-4b5e9a97e00d.png)

**Comment by cgreene** [comment]
Let's:
* Add the number of quants files generated in the last unit time.
* Report per unit time on exec dashboard - break up "individual samples processed" from "samples made available for download" (now reported)
