### ISSUE TITLE
Map "Platform" name to certain constants

### ISSUE THREAD

**Issue by arielsvn** [AlexsLemonade/refinebio-frontend#74]
Right now, the Platform names are verbose so they need to be mapped to pretty constants.

**Comment by ramenhog** [comment]
Just talked to Rich and he mentioned that there's a ticket to do this in the backend, so we don't have to worry about it in the frontend: https://github.com/AlexsLemonade/refinebio/pull/308/files#r194175774

Also, Rich suggested that instead of putting manufacturer in the experiment "info bar", we should be putting Technology (like "Microarray").

**Comment by arielsvn** [comment]
I asked @dvenprasad about changing the experiment info bar:

> So when we discussed the experiment page, we decided that we would display the platform information as this piece of information is more valuable to users. Besides most users can infer the technology based on the platform. Also, I think we decided that icons would change based on technology. m for microarray and R for RNA-seq.
> Unless, something has changed since we last discussed this... i.e additional constraints, I do not think we should display technology instead of platform.

**Comment by jaclyn-taroni** [comment]
I agree with @dvenprasad and was going to comment to this effect!
