### ISSUE TITLE
Display alternate accessions on experiment page.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/refinebio-frontend#871]
We store an `alternate_accession` field in the database for experiments because a lot of experiments are in both GEO and Array Express. https://github.com/AlexsLemonade/refinebio/issues/2186 is also going to populate this field with GEO accessions for SRA experiments.

We should add a field to the experiments page to display this.

**Comment by arielsvn** [comment]
@dvenprasad I think you might have mentioned this before, do we have a design with the alternate accession code?

**Comment by dvenprasad** [comment]
No, we don't have a design to show alternate accession codes. I think it makes sense to address this and https://github.com/AlexsLemonade/refinebio/issues/2187 in the same sprint since that is when users may start seeing results with a different accession.

The change should be pretty minor. Off the bat, we can add it as another field on at the experiment level but it is more important for it to be visible on the result card to understand why something with a different accession showed up.

**Comment by kurtwheeler** [comment]
As part of this also turn these accession codes into links (the link is a url template that just needs an accession code).

**Comment by dvenprasad** [comment]
**Experiment result cards:**
<img width="706" alt="Screen Shot 2020-06-22 at 11 53 21 AM" src="https://user-images.githubusercontent.com/15315514/85308434-34542f00-b47f-11ea-9a38-04f6cb5080e7.png">


<img width="700" alt="Screen Shot 2020-06-22 at 11 53 33 AM" src="https://user-images.githubusercontent.com/15315514/85308429-33bb9880-b47f-11ea-88b3-ec858ff618e6.png">



**Experiment Page**

![experiment-page-not-atlernate-accessions](https://user-images.githubusercontent.com/15315514/85308444-37e7b600-b47f-11ea-8c69-518042e57324.png)
