### ISSUE TITLE
Get organism genome build and version information dynamically for sample processing modals

### ISSUE THREAD

**Issue by ramenhog** [AlexsLemonade/refinebio-frontend#99]
Relies on this issue: https://github.com/AlexsLemonade/refinebio/issues/163

**Comment by jaclyn-taroni** [comment]
I edited the title to reflect the fact that we will have different genome build information for every individual organism

**Comment by Willv19** [comment]
@dvenprasad @jaclyn-taroni Where on the frontend do we want this information?

**Comment by jaclyn-taroni** [comment]
The processing information modals, see: https://github.com/AlexsLemonade/refinebio-frontend/issues/22 and https://github.com/AlexsLemonade/refinebio-frontend/pull/50. Let us know if that doesn't clarify things!

**Comment by arielsvn** [comment]
@dongbohu is there an api for this?? I noticed that https://github.com/AlexsLemonade/refinebio/pull/313#issuecomment-398153073 wasn't merged since the approach to solve this changed.

Also found https://github.com/AlexsLemonade/refinebio/pull/346 which seems to update the models.

**Comment by dongbohu** [comment]
@arielsvn Yes, the API is has been written but it is not completely working yet. I am working on a PR that fixes the backend for this API. When that PR is done, the API should work.

**Comment by arielsvn** [comment]
Great to hear @dongbohu! Please ping me when that PR is done to finish this issue.

**Comment by arielsvn** [comment]
@dongbohu I was checking in staging after the last deploy... I think the samples processor information is not being returned correctly. Check [here](https://api.staging.refine.bio/samples/?accession_codes=GSM414029) for example.

It's returning a number instead of the processor information

![image](https://user-images.githubusercontent.com/1882507/44158190-24e54d00-a082-11e8-9e89-6888d1f71839.png)

I'm missing something?

**Comment by dongbohu** [comment]
I think `1` is the processor ID. You can get more details of processors by:
https://api.staging.refine.bio/processors/

I will modify the backend to support the API like `https://api.staging.refine.bio/processors/1`.

**Comment by arielsvn** [comment]
> I will modify the backend to support the API like https://api.staging.refine.bio/processors/1.

In the future there will be a big number of processors?? I see we only have 5 on staging right now. We can also do a single request to `/processors` and save that information in the front end, to avoid having to make individual requests for each processor. What do you think?

**Comment by dongbohu** [comment]
Right now we have 11 types of processors (some of them are not created in the database because they are not being used). So it is feasible to get all processors in one request and cache them on the front end. 

But in the future each new deployment or update of runtime environment may create new processor  records in the database. So an API like `https://api.staging.refine.bio/processors/1` will still be a good idea to have in the long run.

**Comment by jaclyn-taroni** [comment]
Based on the conversation on the ticket and chatting with folks, it sounds like this encompasses the genome build _and_ the version information. I will update the title to reflect that.

**Comment by arielsvn** [comment]
I'm having difficulties finding the place to get the genome build info. I think it's being stored in `OrganismIndex.source_version`: https://github.com/AlexsLemonade/refinebio/blob/dev/common/data_refinery_common/models/models.py#L509

It seems to be exposed by the `OrganismIndexSerializer` as well https://github.com/AlexsLemonade/refinebio/blob/dev/api/data_refinery_api/serializers.py#L57

But I can't find the endpoint where this is exposed. @dongbohu do you have any idea?

**Comment by arielsvn** [comment]
Thanks to @dongbohu and @Miserlou, found the API that retrieves `OrganismIndex` information:

https://api.staging.refine.bio/transcriptome_indices/?organism=DANIO_RERIO&length=long

```json
{
    "s3_url": "data-refinery-s3-transcriptome-index-circleci-staging.s3.amazonaws.com/DANIO_RERIO_TRANSCRIPTOME_LONG.tar.gz",
    "source_version": "93",
    "salmon_version": "salmon 0.9.1",
    "last_modified": "2018-08-15T19:32:08.141487Z"
}
```

@jaclyn-taroni to confirm, genome information would be the `source_version` in the above response?

**Comment by jaclyn-taroni** [comment]
The `source_version` is referencing the Ensembl release version
<img width="268" alt="screen shot 2018-08-29 at 3 11 53 pm" src="https://user-images.githubusercontent.com/19534205/44809841-e2e9fa00-ab9d-11e8-8c07-e7863c1e34b6.png">

Rather than the genome version, which would be `GRCz11` for zebrafish right now: http://useast.ensembl.org/Danio_rerio/Info/Index

The genome build version is what will be of interest to most users.

**Comment by arielsvn** [comment]
closed by https://github.com/AlexsLemonade/refinebio-frontend/pull/280#issuecomment-418502873
